.github/workflows/ci.yml, pyproject.toml, src/docket/docket.py, src/docket/worker.py, tests/test_fundamentals.py
We want to have some optionality about rescheduling future work, so that
we can either leave an already task scheduled with `add` alone, or we
can `replace` it with a new schedule and parameters.
=> Splits off a `replace` that reschedules tasks from the idempotent `add`

src/docket/__init__.py, src/docket/dependencies.py, src/docket/docket.py, src/docket/worker.py, tests/conftest.py, tests/test_dependencies.py, tests/test_fundamentals.py, tests/test_worker.py
Here I'm formalizing the idea of the `Dependency` task parameters, with
a convention that dependency subclasses are callable to return the
actual value they will give the to the task at runtime.  They are given
the current docket, worker, and execution as context, but they can
return any value.
I've introduced `CurrentDocket` and `CurrentWorker`, and I've reworked
`Retry` to this framework.
=> Introduces a more formalized `Dependency` approach

.github/workflows/chaos.yml, .github/workflows/ci.yml, chaos/README.md, chaos/driver.py, chaos/producer.py, chaos/tasks.py, chaos/worker.py, src/docket/__init__.py, src/docket/dependencies.py, src/docket/docket.py, src/docket/worker.py, tests/test_fundamentals.py, tests/test_worker.py
This suite gives us a way to test some of the resiliency features of
`docket` in ways that are challenging to the unit test suite.  Here we
can run many processes, crash them, even restart the redis server in
order to see how the system behaves.
As a fun side note, I got some extra help with chaos testing here
because on my system I would often overload the proxy started by
`testcontainers` and cause errors connecting to redis throughout.  This
gave me a lot of real-world examples of places to handle errors in a
safer way.
This also required implementing `Worker.run_forever`, which is now in
place, if a little kludgey.
Closes #16
Part of #8
=> Adds a chaos testing suite

pyproject.toml, src/docket/cli.py, src/docket/docket.py, src/docket/instrumentation.py, src/docket/worker.py, tests/conftest.py, tests/test_instrumentation.py, tests/test_worker.py, uv.lock
Here we use the OpenTelemetry metric objects to implement docket actions
like adding, cancelling, starting, or retrying tasks.  Using this
approach with the OpenTelemetry metrics gives us Prometheus support for
virtually free by using `opentelemetry-exporter-prometheus`, which will
automatically start a webserver when used with
`opentelemetry-instrument`.  When we work on configuring and starting
the worker, we can also bring in the couple lines of OTEL object setup
that would require.
Closes #11
=> Adds metrics for all activities, in OpenTelemetry and Prometheus

pyproject.toml, src/docket/cli.py, src/docket/tasks.py, src/docket/worker.py, tests/cli/test_trace.py, tests/cli/test_worker.py, uv.lock
`rich` is doing most of the heavy lifting here for making the logging
output delightful.  I came up with a compact notation for showing the
start, end, and retry status of tasks using Unicode arrows, totally open
to feedback on that.
The plain format may need to be even plainer, but I just started there
as a starting point.
With the JSON format, I wasn't entirely sure which standard library
fields folks would want so I'm keeping it just to the level and time.
Closes #23
Rich:
Plain (automatically picked because `| cat` means not in an interactive TTY):
JSON:
=> Sets up `rich`, plain, and JSON logging for the worker

src/docket/__init__.py, src/docket/annotations.py, src/docket/execution.py, src/docket/worker.py, tests/test_fundamentals.py
The tests have a good illustration of this:
```
async def test_tasks_can_opt_into_argument_logging(
docket: Docket, worker: Worker, caplog: pytest.LogCaptureFixture
):
"""Tasks can opt into argument logging for specific arguments"""
async def the_task(
a: Annotated[str, Logged],
b: str,
c: Annotated[str, Logged()] = "c",
d: Annotated[str, "nah chief"] = "d",
docket: Docket = CurrentDocket(),
):
pass
await docket.add(the_task)("value-a", b="value-b", c="value-c", d="value-d")
with caplog.at_level(logging.INFO):
await worker.run_until_finished()
assert "the_task('value-a', b=..., c='value-c', d=...)" in caplog.text
assert "value-b" not in caplog.text
assert "value-d" not in caplog.text
```
Here, the log line mostly looks like what the equivalent Python call would, but unlogged arguments are …
=> Supports opt-in argument logging

tests/test_fundamentals.py
Just wanted to demonstrate that a task can be scheduled while it is
currently running.  This just uses `docket.add`, but later we could
think about making self-perpetuating tasks first-class citizens.
Closes #7
=> Adds tests for self-perpetuating tasks

chaos/driver.py, src/docket/cli.py, src/docket/docket.py, src/docket/worker.py, tests/test_fundamentals.py, tests/test_worker.py
The `prefetch_count` parameter has been replaced with a new
`concurrency` parameter that governs the maximum number of tasks that
are allowed to run concurrently, as well as how much if retriveed from
the Redis stream on each pass.
Big thanks to `claude-3.7-thinking` for the careful implementation.  I
did have to clean this up a good bit, but it got the framework down.
Closes #39
=> Adds support for concurrent execution of tasks

src/docket/execution.py, src/docket/worker.py, tests/test_fundamentals.py, tests/test_striking.py, tests/test_worker.py
Here we add tests showing that a few user-driven errors from passing
bad arguments and strike values could cause crashes.
Closes #38
=> Handles cases where bad user data could crash a worker

src/docket/cli.py, src/docket/docket.py, src/docket/execution.py, tests/cli/test_striking.py
This lets you say things like:
```
docket strike my_task my_arg == hello    # defaults to a string
docket strike my_task my_arg == int:123
docket strike my_task my_arg == float:123
docket strike my_task my_arg == uuid.UUID:4d071723-60ae-4897-93d2-b2ee27b16b43
docket strike my_task my_arg == pendulum.parse:2025-01-02
```
Closes #35
=> Adds support for type coercion for the strike/restore CLI tasks

src/docket/cli.py, src/docket/docket.py, src/docket/worker.py, tests/cli/test_workers.py, tests/test_worker.py
Workers now send a heartbeat periodically, including which tasks they
are currently configured to run.  This allows for querying by all
workers on a docket, as well as all workers available for a specific
task.
Closes #24
=> Adds worker heartbeats

pyproject.toml, src/docket/cli.py, src/docket/docket.py, src/docket/tasks.py, src/docket/worker.py, tests/cli/test_snapshot.py, tests/cli/test_tasks.py, tests/test_docket.py, tests/test_worker.py, uv.lock
Here we print out a status report of the state of the docket, including
* How many workers are running
* How many total tasks are in queue/scheduled
* How many tasks are running now
* A table of the nearest 1,000 tasks, with the worker they are running
on if they are currently in-flight
Closes #10
=> Adds a `docket snapshot` command to print the state of the docket

src/docket/__main__.py, src/docket/cli.py, tests/cli/test_module.py, tests/cli/test_snapshot.py, tests/cli/test_striking.py, tests/cli/test_worker.py, tests/cli/test_workers.py, tests/conftest.py
I'd underestimated how much slower the test suite was with the subprocesses, until I noticed that each subprocess created its own intermediate `coverage` output file.  Then I realized that coverage needed to instrument all the code for each subprocess invocation.
=> Uses `CliRunner` instead of subprocesses for faster testing

src/docket/worker.py
Under some circumstance, `xautoclaim` will only return 2 elements
instead of 3.  This appears to be the case with either `redis==4.6.0` or
Redis 6, based on some empirical testing.  In either case, we're only
interested in the second element (the messages), so we can safely handle
either response.
=> Handles `XAUTOCLAIM` responses with only 2 elements.

pyproject.toml, tests/conftest.py
This uses `pytest-xdist` for splitting tests over multiple processes,
and coordinates the workers to create a single redis container, with
each worker using a different DB.  This allows for up to 15 workers (as
we hold off db=15 itself to be for bookkeeping of the test suite).
With some emperical testing, I found that 4 workers results in the
lowest runtime right now.
Closes #71
=> Runs tests in parallel

src/docket/worker.py, tests/conftest.py, tests/test_fundamentals.py
After a few iterations trying to get this to work with strikes, I
decided to try it with task keys and things ended up much simpler.  The
`_strike_conditions` is a nice facility that may come in handy for
some other applications in the future (not sure yet, though).  Works
like a charm for this one.
Closes #58
=> Adds a testing utility for self-perpetuating tasks

.pre-commit-config.yaml, src/docket/__init__.py, src/docket/dependencies.py, src/docket/instrumentation.py, src/docket/worker.py, tests/test_fundamentals.py, tests/test_worker.py
With the new `Perpetual` dependency, a user can request that a task
automatically perpetuate itself indefinitely.  `Perpetual` gives an
API for cancelling the chain of tasks, as well as adjusting parameters
between executions.
The typing for `perpetual.perpetuate(*args, **kwargs)` isn't aware of
the tasks' function signature, and I'm not sure how that would be
possible without requiring the user to make some pretty onerous generics
and a `Protocol` representing the task.
=> First-class support for self-perpetuating tasks

src/docket/execution.py, src/docket/worker.py, tests/conftest.py, tests/test_worker.py
While trying to integrate docket `Perpetual` and `run_at_most` in a
real-world project that has longer time horizons between tasks, I
noticed that the test suite was hanging because we were actually
scheduling the new task and then waiting for it it come due.
=> Checks for maximum execution counts at both execution and scheduling

src/docket/worker.py
I'm not entirely sure exactly under which conditions this can happen,
but it's easy enough to handle here.
Closes #83
=> Avoids errors when a `None` messages comes back from redis

chaos/driver.py, chaos/producer.py
About half of the tasks here will now be shortly in the future, meaning
we'll have more work to do in the scheduling of due tasks Lua script.
On my laptop (admittedly kind of a beast), I've gotten speeds of > 5k
tasks per second through on shorter runs with small numbers of workers.
When cranking up to 500 workers against a single redis, I can routinely
get > 800/s (which crushes my machine peaking out around 5k redis
clients connected at once).  With 100 workers, I can get > 2.8k/s.
=> Makes the chaos tests a little more interesting with future tasks

src/docket/cli.py, src/docket/worker.py, tests/conftest.py
This is an optimization I've had my eye on for a bit: we don't need to
go out to the future schedule queue as frequently as we need to work
tasks on the stream.  Here, I've split that loop out separately from the
worker loop, and given it a separately configurable scheduling
resolution setting.
=> Decouples the scheduling of due tasks from the working of them

examples/common.py, examples/find_and_flood.py, src/docket/docket.py, src/docket/worker.py, tests/test_worker.py
Working through the stripped down find & flood example, I noticed all
sorts of problems when running multiple workers with these quick tasks.
First, right off the bat, we had massive race condition in
`Docket.schedule` where two processes could both check if the task was
already scheduled, both see "nope", and then both proceed to schedule
the tasks.  I was seeing massive overscheduling of quick tasks.
Next, the loop for constantly adding perpetual tasks was deeply flawed
because it had no context or memory of the timing of the task's natural
rescheduling, so it would often just jump in an reschedule a task right
as it was starting.  I realized that the far more reliable thing was to
preemptively reschedule the task in the future just before executing
it, so if there was any problem after …
=> Fixing a myriad of race conditions

src/docket/__init__.py, src/docket/dependencies.py, src/docket/worker.py, tests/conftest.py, tests/test_fundamentals.py, tests/test_worker.py
=> Adds extendable timeouts

chaos/tasks.py, src/docket/dependencies.py, src/docket/execution.py, src/docket/worker.py, tests/test_fundamentals.py, tests/test_worker.py
This enables the full suite of dependency injection, with dependencies
being able to ask for their own dependencies (with caching).  This
brings the parity with FastAPI and pytest pretty darn close.
Closes #104
=> Adds dependencies-of-dependencies with caching

examples/common.py, examples/find_and_flood.py, pyproject.toml, src/docket/__main__.py, src/docket/docket.py, src/docket/execution.py, src/docket/worker.py, tests/test_execution.py, tests/test_worker.py, uv.lock
Closes #115
Closes #114
I also noticed that the default task keys were prefaced with the function name, which is where most of the redundancy in `docket snapshot` was coming from.  Using `uuid7` makes these more compact and also look cooler.
Closes #116
=> Making startup logs look less bad

src/docket/dependencies.py, tests/test_dependencies.py
Closes https://github.com/chrisguidry/docket/issues/129
=> Add `in_` and `at` helpers to allow for directly requesting a retry
